config/routes.rb
Food::Application.routes.draw do
  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :orders

  namespace :admin do
    devise_for :users
    resources :dishes , :categories , :order_dishes ,:orders ,:import_tables, :locations

    delete 'destroy_all_dises' => 'dishes#destroy_all'
    post 'import_tables/:id' => 'import_tables#merge'
    get "csv/import", :as => :import_csv
    post "csv/import" => 'csv#upload'
  end

  match 'admin' => 'admin/dashboard#index', :as => :admin_dashboard
  match 'admin/dashboard/:date' => 'admin/dashboard#show', :as => :admin_dashboard_show

  root :to => "orders#index"
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::AdminController
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to(admin_locations_url, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(admin_locations_url, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(admin_locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.haml
= form_for [:admin,@location] do |f|
  -if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/admin/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Back', admin_locations_path

app/views/admin/locations/index.html.haml
%h1 Listing locations

%table
  %thead
    %tr
      %th Name
      %th Address
      %th Phone
      %th
      %th

  - @locations.each do |location|
    %tr
      %td= location.name
      %td= location.address
      %td= location.phone
      %td= link_to 'Edit', edit_admin_location_path(location)
      %td= link_to 'Destroy', admin_location_path(location), :confirm => 'Are you sure?', :method => :delete , :class=>"red"

%br

= link_to 'New Location', new_admin_location_path

app/views/admin/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', admin_locations_path

app/views/admin/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Address:
  = @location.address
%p
  %b Phone:
  = @location.phone

= link_to 'Edit', edit_admin_location_path(@location)
\|
= link_to 'Back', admin_locations_path