config/routes.rb
Food::Application.routes.draw do
  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :orders

  namespace :admin do
    devise_for :users
    resources :dishes , :categories , :order_dishes ,:orders ,:import_tables, :locations

    delete 'destroy_all_dises' => 'dishes#destroy_all'
    post 'import_tables/:id' => 'import_tables#merge'
    get "csv/import", :as => :import_csv
    post "csv/import" => 'csv#upload'
  end

  match 'admin' => 'admin/dashboard#index', :as => :admin_dashboard
  match 'admin/dashboard/:date' => 'admin/dashboard#show', :as => :admin_dashboard_show

  root :to => "orders#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishes
  validates :name,  :presence => true,
                    :uniqueness => true,
                    :length => {:minimum => 3, :maximum => 254}
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  WEEK_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'all_days']
  belongs_to :category
  has_many :order_dishes, :dependent => :destroy
  has_many :orders, :through => :order_dishes

  validates :name,  :presence => true,
            :length => {:minimum => 3, :maximum => 254}

  validates :description,  :presence => true,
            :uniqueness => true

  validates :price,  :presence => true

  validates :category_id,  :presence => true


  def self.week_day_dishes week_day
    where("week_day = ? OR week_day = ?", week_day, 6).includes(:category).order(:category_id).order(:id)
  end

  def self.tomorrow_dishes
    where("week_day = ? OR week_day = ?", Dish.next_work_day, 6).includes(:category).order(:category_id).order(:id)
  end

  def self.next_work_day
    if Time.now.wday != 5
      Time.now.wday+1
    else
      1
    end
  end
end

app/models/import_cell.rb
class ImportCell < ActiveRecord::Base
  belongs_to :import_table
end

app/models/import_table.rb
class ImportTable < ActiveRecord::Base
  has_many :import_cells, :dependent => :destroy
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_dishes, :dependent => :destroy
  has_many :dishes, :through => :order_dishes
  belongs_to :user

  attr_accessor :dish_ids
  after_save :update_dishes

  def update_dishes
    unless dish_ids.nil?
      self.order_dishes.each do |o|
        o.destroy unless dish_ids.include?(o.dish_id.to_s)
        dish_ids.delete(o.dish_id.to_s)
      end
      dish_ids.each do |d|
        self.order_dishes.create(:dish_id => d) unless d.blank?
      end
      reload
      self.dish_ids = nil
    end
  end

  def self.orders_by_date date
    where('DATE(created_at) = ?', date)
  end

  def self.previous_order_grouped
    find(:all, :select => 'distinct date(created_at) as date').map(&:date)
  end

end

app/models/order_dish.rb
class OrderDish < ActiveRecord::Base
  belongs_to :order
  belongs_to :dish

  def self.orders_dishes_width_count date
    find(:all,
         :joins => "LEFT JOIN dishes on order_dishes.dish_id = dishes.id LEFT JOIN orders on order_dishes.order_id = orders.id" ,
         :select => "dish_id, COUNT(*) AS cnt",
         :group =>"dishes.category_id, order_dishes.dish_id",
         :conditions => ["DATE(orders.created_at) = ?", date],
         :order => "dishes.category_id"
    )


    #select("dish_id, COUNT(*) AS cnt").group('dish_id').where('DATE(order_dishes.created_at) = ?', Date.today)

    #find_by_sql("SELECT *, COUNT(*) AS cnt FROM order_dishes  od WHERE DATE(created_at) = '#{Date.today}' GROUP BY dish_id;")
    #today =Time.now.midnight .. (Time.now.midnight + 1.day)
    #joins(:orders).where(:orders => {:created_at => today})
    #find(:all, :select => "*, COUNT(*) AS cnt", :where=>"DATE(created_at) = \"#{Date.today}\"", :group => "order_dishes.dish_id")
  end

  def self.today_orders
    where('DATE(created_at) = ?', Date.today)
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :orders

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token['user_info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end


end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  def get_order_and_dishes_by_data data
    @orders = Order.orders_by_date data
    @orders_dishes_width_count = OrderDish.orders_dishes_width_count data
    @grand_total=0
    @orders_dishes_width_count.each do |c|
      @grand_total += c.dish.price.to_f*c.cnt.to_f
    end
    @previous_order = Order.previous_order_grouped
  end

  def index
    get_order_and_dishes_by_data Date.today
  end

  def show
    get_order_and_dishes_by_data params[:date]
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :admin_redirect
  # GET /orders
  # GET /orders.xml
  def admin_redirect
    if current_user.email=='admin@gmail.com'
      redirect_to admin_dashboard_path
    end
  end

  def index
    @orders = current_user.orders



    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    @order = current_user.orders.find(params[:id])
    @dishes = @order.dish

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new
    @dishes = Dish.tomorrow_dishes

    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = current_user.orders.find(params[:id])
  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])
    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to(orders_url, :notice => 'Order was successfully created.') }
        format.xml  { render :xml => @order, :status => :created, :location => @order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    @order = current_user.orders.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to(orders_url, :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.xml
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to(orders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_today_created k
    k.created_at.to_date == Date.today
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/import_tables_helper.rb
module ImportTablesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/order_dishes_helper.rb
module OrderDishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/dashboard/_menu.html.haml
%ul
  %li= link_to "Home", admin_dashboard_path
  %li= link_to "Locations", admin_locations_path
  %li= link_to "Categories", admin_categories_path
  %li= link_to "Dishes", admin_dishes_path
  %li= link_to "Orders", admin_orders_path
  %li= link_to "Import CSV", admin_import_csv_path
  %li=link_to "Sign out", destroy_user_session_path , :method => :delete, :class=>'red'

app/views/admin/dashboard/index.html.haml
%h1 Тел: 56-60-26,  Адрес: Шевченка 396 к180
%h2 Today orders
%table
  %thead
    %tr
      %th id
      %th user
      %th data
      %th dishes

  - @orders.each do |order|
    %tr
      %td= order.id
      %td= order.user.email
      %td= order.created_at.to_date
      %td.aright
        - order.dishes.each do |dish|
          =dish.name+" #{dish.category.name.to_s[0..1]} (#{dish.price})"
        %span.green="sum: #{order.dishes.sum('price')} Грн."

%h2 Report

%table
  %thead
    %tr
      %th Category
      %th Name
      %th Description
      %th Сount
      %th Price
      %th Total

  - @orders_dishes_width_count.each do |cod|
    %tr{:class=>"color_#{cod.dish.category.id}"}
      %td= cod.dish.category.name
      %td= cod.dish.name
      %td= cod.dish.description
      %td= cod.cnt
      %td= cod.dish.price
      %td.aright="#{cod.dish.price.to_f*cod.cnt.to_f} Грн."
  %tr
    %td
    %td
    %td
    %td
    %td
    %td.green="SUM: #{@grand_total} ГРН."

%h2 Previous reports
%ul
  - @previous_order.each do |po|
    %li=link_to po , admin_dashboard_show_path(:date => po)

app/views/admin/dashboard/show.html.haml
%h1 Тел: 56-60-26,  Адрес: Шевченка 396 к180
%br

%h2="Order by #{params[:date]}"
%table
  %thead
    %tr
      %th id
      %th user
      %th data
      %th dishes

  - @orders.each do |order|
    %tr
      %td= order.id
      %td= order.user.email
      %td= order.created_at
      %td.aright
        - order.dishes.each do |dish|
          =dish.name+" #{dish.category.name.to_s[0..1]} (#{dish.price})"
        %span.green="sum: #{order.dishes.sum('price')} Грн."

%h2="Report by #{params[:date]}"

%table
  %thead
    %tr
      %th Category
      %th Name
      %th Description
      %th Сount
      %th Price
      %th Total

  - @orders_dishes_width_count.each do |cod|
    %tr{:class=>"color_#{cod.dish.category.id}"}
      %td= cod.dish.category.name
      %td= cod.dish.name
      %td= cod.dish.description
      %td= cod.cnt
      %td= cod.dish.price
      %td.aright="#{cod.dish.price.to_f*cod.cnt.to_f} Грн."
  %tr
    %td
    %td
    %td
    %td
    %td
    %td.green="SUM: #{@grand_total} ГРН."