config/routes.rb
Food::Application.routes.draw do
  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :orders

  namespace :admin do
    devise_for :users
    resources :dishes , :categories , :order_dishes ,:orders ,:import_tables, :locations

    delete 'destroy_all_dises' => 'dishes#destroy_all'
    post 'import_tables/:id' => 'import_tables#merge'
    get "csv/import", :as => :import_csv
    post "csv/import" => 'csv#upload'
  end

  match 'admin' => 'admin/dashboard#index', :as => :admin_dashboard
  match 'admin/dashboard/:date' => 'admin/dashboard#show', :as => :admin_dashboard_show

  root :to => "orders#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishes
  validates :name,  :presence => true,
                    :uniqueness => true,
                    :length => {:minimum => 3, :maximum => 254}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(admin_categories_url, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(admin_categories_url, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(admin_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category] do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/admin/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', admin_category_path( @category )
\|
= link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Edit', edit_admin_category_path(category)
      %td= link_to 'Destroy', admin_category_path(category), :confirm => 'Are you sure?', :method => :delete, :class=>'red'

%br

= link_to 'New Category', new_admin_category_path

app/views/admin/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_admin_category_path(@category)
\|
= link_to 'Back', admin_categories_path