config/routes.rb
Food::Application.routes.draw do
  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :orders

  namespace :admin do
    devise_for :users
    resources :dishes , :categories , :order_dishes ,:orders ,:import_tables, :locations

    delete 'destroy_all_dises' => 'dishes#destroy_all'
    post 'import_tables/:id' => 'import_tables#merge'
    get "csv/import", :as => :import_csv
    post "csv/import" => 'csv#upload'
  end

  match 'admin' => 'admin/dashboard#index', :as => :admin_dashboard
  match 'admin/dashboard/:date' => 'admin/dashboard#show', :as => :admin_dashboard_show

  root :to => "orders#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishes
  validates :name,  :presence => true,
                    :uniqueness => true,
                    :length => {:minimum => 3, :maximum => 254}
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  WEEK_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'all_days']
  belongs_to :category
  has_many :order_dishes, :dependent => :destroy
  has_many :orders, :through => :order_dishes

  validates :name,  :presence => true,
            :length => {:minimum => 3, :maximum => 254}

  validates :description,  :presence => true,
            :uniqueness => true

  validates :price,  :presence => true

  validates :category_id,  :presence => true


  def self.week_day_dishes week_day
    where("week_day = ? OR week_day = ?", week_day, 6).includes(:category).order(:category_id).order(:id)
  end

  def self.tomorrow_dishes
    where("week_day = ? OR week_day = ?", Dish.next_work_day, 6).includes(:category).order(:category_id).order(:id)
  end

  def self.next_work_day
    if Time.now.wday != 5
      Time.now.wday+1
    else
      1
    end
  end
end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < Admin::AdminController
  # GET /dishes
  # GET /dishes.xml
  def index
    @dishes = Dish.includes(:category).order("week_day").order("category_id").all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.xml
  def show
    @dish = Dish.find(params[:id])

    @import_cells = @import_table.import_cells
    @row_index_max = @import_cells.map { |cell| cell.row_index }.max
    @column_index_max = @import_cells.map { |cell| cell.column_index }.max

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.xml
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.haml
      format.xml  { render :xml => @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.xml
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to(admin_dishes_url, :notice => 'Dish was successfully created.') }
        format.xml  { render :xml => @dish, :status => :created, :location => @dish }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.xml
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to(admin_dishes_url, :notice => 'Dish was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dish.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.xml
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to(admin_dishes_url) }
      format.xml  { head :ok }
    end
  end

  def destroy_all
    @all_dish = Dish.all
    @all_dish.each do |all_dish|
      all_dish.destroy
    end

    respond_to do |format|
      format.html { redirect_to(admin_dishes_url) }
      format.xml  { head :ok }
    end
  end


end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/admin/dishes/_form.html.haml
= form_for [:admin, @dish ] do |f|
  -if @dish.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dish.errors.count, "error")} prohibited this dish from being saved:"
      %ul
        - @dish.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :week_day
    =# f.select :week_day, Dish::WEEK_DAYS, :prompt => 'chose'
    = f.select(:week_day, Dish::WEEK_DAYS.collect {|d| [d, Dish::WEEK_DAYS.index(d)+1]})

  .field
    = f.label :category_id
    = f.collection_select :category_id, Category.find(:all), :id, :name, :prompt => "chose"

  .actions
    = f.submit 'Save'

app/views/admin/dishes/_list.html.haml
%table
  %tr
    %th Check
    %th Category
    %th Name
    %th Description
    %th Weight
    %th Price


  -# dishes.each do |dish|
  = hidden_field_tag "order[dish_ids][]", ""
  - for dish in Dish.tomorrow_dishes
    %tr{:class=>"color_#{dish.category.id}"}
      %td= check_box_tag "order[dish_ids][]", dish.id, @order.dishes.include?(dish)
      %td= dish.category.name
      %td= dish.name
      %td= dish.description
      %td= dish.weight
      %td= dish.price

app/views/admin/dishes/edit.html.haml
%h1 Editing dish

= render 'form'

= link_to 'Show', admin_dish_path(@dish)
\|
= link_to 'Back', admin_dishes_path

app/views/admin/dishes/index.html.haml
%h1 Listing dishes

%table
  %thead
    %tr
      %th Category
      %th Name
      %th Description
      %th Price
      %th Weight
      %th Week day
      %th
      %th

  - @dishes.each do |dish|
    %tr{:class=>"color_#{dish.category.id}"}
      %td= dish.category.name
      %td= dish.name
      %td= dish.description
      %td= dish.price
      %td= dish.weight
      %td= dish.week_day
      %td= link_to 'Edit', edit_admin_dish_path(dish)
      %td= link_to 'Destroy', admin_dish_path(dish), :confirm => 'Are you sure?', :method => :delete, :class=>'red'

%br

= link_to 'New Dish', new_admin_dish_path

%br
%br
%br

%td= link_to 'Destroy ALL !!!', admin_destroy_all_dises_path, :confirm => 'Are you sure?', :method => :delete, :class=>'red'

app/views/admin/dishes/new.html.haml
%h1 New dish

= render 'form'

= link_to 'Back', admin_dishes_path

app/views/admin/dishes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @dish.name
%p
  %b Description:
  = @dish.description
%p
  %b Price:
  = @dish.price
%p
  %b Weight:
  = @dish.weight
%p
  %b Week day:
  = @dish.week_day
%p
  %b Category:
  = @dish.category_id

= link_to 'Edit', edit_admin_dish_path(@dish)
\|
= link_to 'Back', admin_dishes_path